services:

  auth-service:
    build:
      context: ./springboot-jwt-auth
    ports:
      - "8089:8089"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  patient-service:
    build:
      context: ./PatientManagement
    ports:
      - "8081:8081"
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  location-service:
    build:
      context: ./LocationManagement
    ports:
      - "8082:8082"
    depends_on:
      patient-service:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  alert-service:
    build:
      context: ./AlertManagement
    ports:
      - "8083:8083"
    depends_on:
      location-service:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  microservices-network:

